#!/bin/bash

echo "Welcome to PARTONS" 
echo "See http://partons.cea.fr for description and technical documentation"

if [ $# -eq 0 ]; then
   /bin/bash  
else

   cd /root/workspace/partons-example

   for i in $@; do
      ./bin/PARTONS_example scenarios/$i 
   done
fi
