/* SQLITE syntax */

CREATE TABLE convol_coeff_function_kinematic (
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
xi DOUBLE NOT NULL,
t DOUBLE NOT NULL,
Q2 DOUBLE NOT NULL,
MuF2 DOUBLE NOT NULL,
MuR2 DOUBLE NOT NULL);

CREATE TABLE convol_coeff_function_result (
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
computation_module_name VARCHAR(255) NOT NULL,
convol_coeff_function_kinematic_id INTEGER NOT NULL,
computation_id INTEGER NOT NULL);

CREATE TABLE ccf_result_complex (
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
gpd_type_id INTEGER NOT NULL,
ccf_result_id INTEGER NOT NULL,
complex_id INTEGER NOT NULL);